table hyper_raw_data
	lineageTag: 3cee1588-2921-403c-9a0f-59295bc9a3c0

	column 'Order ID'
		dataType: string
		lineageTag: bd89b95b-5ca2-42fd-8143-8c8de9307364
		summarizeBy: none
		sourceColumn: Order ID

		annotation SummarizationSetBy = Automatic

	column 'Order Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: db898cda-dca9-4df8-9c33-a89e018d84a5
		summarizeBy: none
		sourceColumn: Order Date

		variation Variation
			isDefault
			relationship: fad1e01e-5dd3-456c-9002-c243213517a9
			defaultHierarchy: LocalDateTable_25231830-9031-45c9-b998-9701f625cede.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Ship Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: e1fb9756-5f2e-408a-a012-27339de2c65c
		summarizeBy: none
		sourceColumn: Ship Date

		variation Variation
			isDefault
			relationship: de91073f-575e-4d29-ac97-9ce2450657e2
			defaultHierarchy: LocalDateTable_fe110347-7d15-42b8-9360-d07b68dd6df1.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Ship Mode'
		dataType: string
		lineageTag: 55261774-0775-4799-87b8-97149529ad1a
		summarizeBy: none
		sourceColumn: Ship Mode

		annotation SummarizationSetBy = Automatic

	column 'Customer Name'
		dataType: string
		lineageTag: 0d15675a-2956-4b6a-8620-fcb3f899d9cc
		summarizeBy: none
		sourceColumn: Customer Name

		annotation SummarizationSetBy = Automatic

	column Segment
		dataType: string
		lineageTag: 38494862-7768-4539-960c-41daf5d24617
		summarizeBy: none
		sourceColumn: Segment

		annotation SummarizationSetBy = Automatic

	column Country/Region
		dataType: string
		lineageTag: d28b5728-5f4b-4eab-bcc0-90717e904dd9
		summarizeBy: none
		sourceColumn: Country/Region

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: 79595d8d-412b-4d9e-bf4e-66fd35d91f2d
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column State
		dataType: string
		lineageTag: 4d26f7ff-9e44-44e2-9169-0e1e4e91dfc7
		summarizeBy: none
		sourceColumn: State

		annotation SummarizationSetBy = Automatic

	column 'Postal Code'
		dataType: int64
		formatString: 0
		lineageTag: b6cdfff6-78e2-439b-9520-f72ebd2ec417
		summarizeBy: count
		sourceColumn: Postal Code

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: d0c424a4-0324-4fa5-b6fa-04c25c43dbf8
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: 9c4dc133-1358-48b9-9e27-80d804c2775e
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column Sub-Category
		dataType: string
		lineageTag: 5cd9871f-6981-42ef-a9b4-4db72a7e1887
		summarizeBy: none
		sourceColumn: Sub-Category

		annotation SummarizationSetBy = Automatic

	column 'Product Name'
		dataType: string
		lineageTag: 098a9425-16a1-4d27-9457-e5ea60259be4
		summarizeBy: none
		sourceColumn: Product Name

		annotation SummarizationSetBy = Automatic

	column Sales
		dataType: double
		lineageTag: 378004bf-5052-47ec-9203-f78bb5865b4b
		summarizeBy: sum
		sourceColumn: Sales

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Quantity
		dataType: int64
		formatString: 0
		lineageTag: d8c28776-73a2-4779-818f-ee1ad6b61931
		summarizeBy: sum
		sourceColumn: Quantity

		annotation SummarizationSetBy = Automatic

	column Discount
		dataType: double
		lineageTag: 99969320-72bd-4335-9dd8-23240c8a935d
		summarizeBy: sum
		sourceColumn: Discount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Profit
		dataType: double
		lineageTag: e1d5b611-d44e-4f7a-838e-97e29af8705f
		summarizeBy: sum
		sourceColumn: Profit

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition hyper_raw_data = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\ASUS\Desktop\Tableau-to-Power-BI-semantic-compiler\data\hyper_raw_data.csv"),[Delimiter=",", Columns=18, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Order ID", type text}, {"Order Date", type date}, {"Ship Date", type date}, {"Ship Mode", type text}, {"Customer Name", type text}, {"Segment", type text}, {"Country/Region", type text}, {"City", type text}, {"State", type text}, {"Postal Code", Int64.Type}, {"Region", type text}, {"Category", type text}, {"Sub-Category", type text}, {"Product Name", type text}, {"Sales", type number}, {"Quantity", Int64.Type}, {"Discount", type number}, {"Profit", type number}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

